package javatimefun

import java.time.ZoneId

object ZoneIds {
    val AFRICA_ABIDJAN = ZoneId.of("Africa/Abidjan")
    val AFRICA_ACCRA = ZoneId.of("Africa/Accra")
    val AFRICA_ADDIS_ABABA = ZoneId.of("Africa/Addis_Ababa")
    val AFRICA_ALGIERS = ZoneId.of("Africa/Algiers")
    val AFRICA_ASMERA = ZoneId.of("Africa/Asmera")
    val AFRICA_BAMAKO = ZoneId.of("Africa/Bamako")
    val AFRICA_BANJUL = ZoneId.of("Africa/Banjul")
    val AFRICA_BANGUI = ZoneId.of("Africa/Bangui")
    val AFRICA_BISSAU = ZoneId.of("Africa/Bissau")
    val AFRICA_BLANTYRE = ZoneId.of("Africa/Blantyre")
    val AFRICA_BRAZZAVILLE = ZoneId.of("Africa/Brazzaville")
    val AFRICA_BUJUMBURA = ZoneId.of("Africa/Bujumbura")
    val AFRICA_CAIRO = ZoneId.of("Africa/Cairo")
    val AFRICA_CASABLANCA = ZoneId.of("Africa/Casablanca")
    val AFRICA_CEUTA = ZoneId.of("Africa/Ceuta")
    val AFRICA_CONAKRY = ZoneId.of("Africa/Conakry")
    val AFRICA_DAKAR = ZoneId.of("Africa/Dakar")
    val AFRICA_DAR_ES_SALAAM = ZoneId.of("Africa/Dar_es_Salaam")
    val AFRICA_DJIBOUTI = ZoneId.of("Africa/Djibouti")
    val AFRICA_DOUALA = ZoneId.of("Africa/Douala")
    val AFRICA_EL_AAIUN = ZoneId.of("Africa/El_Aaiun")
    val AFRICA_FREETOWN = ZoneId.of("Africa/Freetown")
    val AFRICA_GABORONE = ZoneId.of("Africa/Gaborone")
    val AFRICA_HARARE = ZoneId.of("Africa/Harare")
    val AFRICA_JOHANNESBURG = ZoneId.of("Africa/Johannesburg")
    val AFRICA_JUBA = ZoneId.of("Africa/Juba")
    val AFRICA_KAMPALA = ZoneId.of("Africa/Kampala")
    val AFRICA_KHARTOUM = ZoneId.of("Africa/Khartoum")
    val AFRICA_KIGALI = ZoneId.of("Africa/Kigali")
    val AFRICA_KINSHASA = ZoneId.of("Africa/Kinshasa")
    val AFRICA_LAGOS = ZoneId.of("Africa/Lagos")
    val AFRICA_LIBREVILLE = ZoneId.of("Africa/Libreville")
    val AFRICA_LUBUMBASHI = ZoneId.of("Africa/Lubumbashi")
    val AFRICA_LUSAKA = ZoneId.of("Africa/Lusaka")
    val AFRICA_MALABO = ZoneId.of("Africa/Malabo")
    val AFRICA_MBABANE = ZoneId.of("Africa/Mbabane")
    val AFRICA_MAPUTO = ZoneId.of("Africa/Maputo")
    val AFRICA_MASERU = ZoneId.of("Africa/Maseru")
    val AFRICA_MOGADISHU = ZoneId.of("Africa/Mogadishu")
    val AFRICA_MONROVIA = ZoneId.of("Africa/Monrovia")
    val AFRICA_NAIROBI = ZoneId.of("Africa/Nairobi")
    val AFRICA_NDJAMENA = ZoneId.of("Africa/Ndjamena")
    val AFRICA_NIAMEY = ZoneId.of("Africa/Niamey")
    val AFRICA_NOUAKCHOTT = ZoneId.of("Africa/Nouakchott")
    val AFRICA_OUAGADOUGOU = ZoneId.of("Africa/Ouagadougou")
    val AFRICA_PORTO_NOVO = ZoneId.of("Africa/Porto-Novo")
    val AFRICA_SAO_TOME = ZoneId.of("Africa/Sao_Tome")
    val AFRICA_TUNIS = ZoneId.of("Africa/Tunis")
    val AFRICA_TRIPOLI = ZoneId.of("Africa/Tripoli")
    val AFRICA_WINDHOEK = ZoneId.of("Africa/Windhoek")

    val AMERICA_ADAK = ZoneId.of("America/Adak")
    val AMERICA_ANGUILLA = ZoneId.of("America/Anguilla")
    val AMERICA_ANTIGUA = ZoneId.of("America/Antigua")
    val AMERICA_ARAGUAINA = ZoneId.of("America/Araguaina")
    val AMERICA_ARGENTINA_Catamarca = ZoneId.of("America/Argentina/Catamarca")
    val AMERICA_ARGENTINA_ComodRivadavia = ZoneId.of("America/Argentina/ComodRivadavia")
    val AMERICA_ARGENTINA_Cordoba = ZoneId.of("America/Argentina/Cordoba")
    val AMERICA_ARGENTINA_Jujuy = ZoneId.of("America/Argentina/Jujuy")
    val AMERICA_ARGENTINA_La_Rioja = ZoneId.of("America/Argentina/La_Rioja")
    val AMERICA_ARGENTINA_Mendoza = ZoneId.of("America/Argentina/Mendoza")
    val AMERICA_ARGENTINA_Rio_Gallegos = ZoneId.of("America/Argentina/Rio_Gallegos")
    val AMERICA_ARGENTINA_Salta = ZoneId.of("America/Argentina/Salta")
    val AMERICA_ARGENTINA_San_Juan = ZoneId.of("America/Argentina/San_Juan")
    val AMERICA_ARGENTINA_San_Luis = ZoneId.of("America/Argentina/San_Luis")
    val AMERICA_ARGENTINA_Ushuaia = ZoneId.of("America/Argentina/Ushuaia")
    val AMERICA_ARGENTINA_Tucuman = ZoneId.of("America/Argentina/Tucuman")
    val AMERICA_ARUBA = ZoneId.of("America/Aruba")
    val AMERICA_BAHIA = ZoneId.of("America/Bahia")
    val AMERICA_BAHIA_BANDERAS = ZoneId.of("America/Bahia_Banderas")
    val AMERICA_BARBADOS = ZoneId.of("America/Barbados")
    val AMERICA_BELIZE = ZoneId.of("America/Belize")
    val AMERICA_BELEM = ZoneId.of("America/Belem")
    val AMERICA_BLANC_SABLON = ZoneId.of("America/Blanc-Sablon")
    val AMERICA_BOGOTA = ZoneId.of("America/Bogota")
    val AMERICA_BOA_VISTA = ZoneId.of("America/Boa_Vista")
    val AMERICA_BOISE = ZoneId.of("America/Boise")
    val AMERICA_CAMBRIDGE_BAY = ZoneId.of("America/Cambridge_Bay")
    val AMERICA_CAMPO_GRANDE = ZoneId.of("America/Campo_Grande")
    val AMERICA_CANCUN = ZoneId.of("America/Cancun")
    val AMERICA_CARACAS = ZoneId.of("America/Caracas")
    val AMERICA_CATAMARCA = ZoneId.of("America/Catamarca")
    val AMERICA_CIUDAD_JUAREZ = ZoneId.of("America/Ciudad_Juarez")
    val AMERICA_CORDOBA = ZoneId.of("America/Cordoba")
    val AMERICA_CURACAO = ZoneId.of("America/Curacao")
    val AMERICA_CUIABA = ZoneId.of("America/Cuiaba")
    val AMERICA_CAYENNE = ZoneId.of("America/Cayenne")
    val AMERICA_CAYMAN = ZoneId.of("America/Cayman")
    val AMERICA_CHICAGO = ZoneId.of("America/Chicago")
    val AMERICA_CHIHUAHUA = ZoneId.of("America/Chihuahua")
    val AMERICA_CRESTON = ZoneId.of("America/Creston")
    val AMERICA_DANMARKSHAVN = ZoneId.of("America/Danmarkshavn")
    val AMERICA_DAWSON = ZoneId.of("America/Dawson")
    val AMERICA_DAWSON_CREEK = ZoneId.of("America/Dawson_Creek")
    val AMERICA_DETROIT = ZoneId.of("America/Detroit")
    val AMERICA_DOMINICA = ZoneId.of("America/Dominica")
    val AMERICA_EDMONTON = ZoneId.of("America/Edmonton")
    val AMERICA_EL_SALVADOR = ZoneId.of("America/El_Salvador")
    val AMERICA_ENSENADA = ZoneId.of("America/Ensenada")
    val AMERICA_EIRUNEPE = ZoneId.of("America/Eirunepe")
    val AMERICA_FORTALEZA = ZoneId.of("America/Fortaleza")
    val AMERICA_FORT_WAYNE = ZoneId.of("America/Fort_Wayne")
    val AMERICA_FORT_NELSON = ZoneId.of("America/Fort_Nelson")
    val AMERICA_GLACE_BAY = ZoneId.of("America/Glace_Bay")
    val AMERICA_GODTHAB = ZoneId.of("America/Godthab")
    val AMERICA_GRAND_TURK = ZoneId.of("America/Grand_Turk")
    val AMERICA_GUADELOUPE = ZoneId.of("America/Guadeloupe")
    val AMERICA_GUATEMALA = ZoneId.of("America/Guatemala")
    val AMERICA_GUAYAQUIL = ZoneId.of("America/Guayaquil")
    val AMERICA_GUYANA = ZoneId.of("America/Guyana")
    val AMERICA_HALIFAX = ZoneId.of("America/Halifax")
    val AMERICA_HAVANA = ZoneId.of("America/Havana")
    val AMERICA_HERMOSILLO = ZoneId.of("America/Hermosillo")
    val AMERICA_INDIANA_Indianapolis = ZoneId.of("America/Indiana/Indianapolis")
    val AMERICA_INDIANA_Knox = ZoneId.of("America/Indiana/Knox")
    val AMERICA_INDIANA_Marengo = ZoneId.of("America/Indiana/Marengo")
    val AMERICA_INDIANA_Petersburg = ZoneId.of("America/Indiana/Petersburg")
    val AMERICA_INDIANA_Tell_City = ZoneId.of("America/Indiana/Tell_City")
    val AMERICA_INDIANA_Vevay = ZoneId.of("America/Indiana/Vevay")
    val AMERICA_INDIANA_Vincennes = ZoneId.of("America/Indiana/Vincennes")
    val AMERICA_INDIANAPOLIS = ZoneId.of("America/Indianapolis")
    val AMERICA_INUVIK = ZoneId.of("America/Inuvik")
    val AMERICA_IQALUIT = ZoneId.of("America/Iqaluit")
    val AMERICA_JAMAICA = ZoneId.of("America/Jamaica")
    val AMERICA_JUNEAU = ZoneId.of("America/Juneau")
    val AMERICA_JUJUY = ZoneId.of("America/Jujuy")
    val AMERICA_KENTUCKY_LOUISVILLE = ZoneId.of("America/Kentucky/Louisville")
    val AMERICA_KENTUCKY_Monticello = ZoneId.of("America/Kentucky/Monticello")
    val AMERICA_KNOX_IN = ZoneId.of("America/Knox_IN")
    val AMERICA_KRALENDIJK = ZoneId.of("America/Kralendijk")
    val AMERICA_LA_PAZ = ZoneId.of("America/La_Paz")
    val AMERICA_LIMA = ZoneId.of("America/Lima")
    val AMERICA_LOS_ANGELES = ZoneId.of("America/Los_Angeles")
    val AMERICA_LOWER_PRINCES = ZoneId.of("America/Lower_Princes")
    val AMERICA_MACEIO = ZoneId.of("America/Maceio")
    val AMERICA_MANAGUA = ZoneId.of("America/Managua")
    val AMERICA_MANAUS = ZoneId.of("America/Manaus")
    val AMERICA_MARTINIQUE = ZoneId.of("America/Martinique")
    val AMERICA_MATAMOROS = ZoneId.of("America/Matamoros")
    val AMERICA_MAZATLAN = ZoneId.of("America/Mazatlan")
    val AMERICA_MERIDA = ZoneId.of("America/Merida")
    val AMERICA_METLAKATLA = ZoneId.of("America/Metlakatla")
    val AMERICA_MEXICO_CITY = ZoneId.of("America/Mexico_City")
    val AMERICA_MENDOZA = ZoneId.of("America/Mendoza")
    val AMERICA_MONCTON = ZoneId.of("America/Moncton")
    val AMERICA_MONTEVIDEO = ZoneId.of("America/Montevideo")
    val AMERICA_MONTREAL = ZoneId.of("America/Montreal")
    val AMERICA_MONTERREY = ZoneId.of("America/Monterrey")
    val AMERICA_NASSAU = ZoneId.of("America/Nassau")
    val AMERICA_NORONHA = ZoneId.of("America/Noronha")
    val AMERICA_NOME = ZoneId.of("America/Nome")
    val AMERICA_NORTH_DAKOTA_Beulah = ZoneId.of("America/North_Dakota/Beulah")
    val AMERICA_NORTH_DAKOTA_Center = ZoneId.of("America/North_Dakota/Center")
    val AMERICA_NORTH_DAKOTA_New_Salem = ZoneId.of("America/North_Dakota/New_Salem")
    val AMERICA_NIPIGON = ZoneId.of("America/Nipigon")
    val AMERICA_NUUK = ZoneId.of("America/Nuuk")
    val AMERICA_NEW_YORK = ZoneId.of("America/New_York")
    val AMERICA_OJINAGA = ZoneId.of("America/Ojinaga")
    val AMERICA_PORTO_ACRE = ZoneId.of("America/Porto_Acre")
    val AMERICA_PORT_OF_SPAIN = ZoneId.of("America/Port_of_Spain")
    val AMERICA_PORTO_VELHO = ZoneId.of("America/Porto_Velho")
    val AMERICA_PANAMA = ZoneId.of("America/Panama")
    val AMERICA_PARAMARIBO = ZoneId.of("America/Paramaribo")
    val AMERICA_PHOENIX = ZoneId.of("America/Phoenix")
    val AMERICA_PUERTO_RICO = ZoneId.of("America/Puerto_Rico")
    val AMERICA_PUNTA_ARENAS = ZoneId.of("America/Punta_Arenas")
    val AMERICA_PANGNIRTUNG = ZoneId.of("America/Pangnirtung")
    val AMERICA_RECIFE = ZoneId.of("America/Recife")
    val AMERICA_REGINA = ZoneId.of("America/Regina")
    val AMERICA_RESOLUTE = ZoneId.of("America/Resolute")
    val AMERICA_ROSARIO = ZoneId.of("America/Rosario")
    val AMERICA_RAINY_RIVER = ZoneId.of("America/Rainy_River")
    val AMERICA_RANKIN_INLET = ZoneId.of("America/Rankin_Inlet")
    val AMERICA_RIO_BRANCO = ZoneId.of("America/Rio_Branco")
    val AMERICA_SANTIAGO = ZoneId.of("America/Santiago")
    val AMERICA_SANTO_DOMINGO = ZoneId.of("America/Santo_Domingo")
    val AMERICA_SAO_PAULO = ZoneId.of("America/Sao_Paulo")
    val AMERICA_SANTA_ISABEL = ZoneId.of("America/Santa_Isabel")
    val AMERICA_SANTAREM = ZoneId.of("America/Santarem")
    val AMERICA_ST_BARTHELEMY = ZoneId.of("America/St_Barthelemy")
    val AMERICA_ST_JOHNS = ZoneId.of("America/St_Johns")
    val AMERICA_ST_KITTS = ZoneId.of("America/St_Kitts")
    val AMERICA_ST_LUCIA = ZoneId.of("America/St_Lucia")
    val AMERICA_ST_THOMAS = ZoneId.of("America/St_Thomas")
    val AMERICA_ST_VINCENT = ZoneId.of("America/St_Vincent")
    val AMERICA_SWIFT_CURRENT = ZoneId.of("America/Swift_Current")
    val AMERICA_THUNDER_BAY = ZoneId.of("America/Thunder_Bay")
    val AMERICA_TEGUCIGALPA = ZoneId.of("America/Tegucigalpa")
    val AMERICA_TIJUANA = ZoneId.of("America/Tijuana")
    val AMERICA_TORONTO = ZoneId.of("America/Toronto")
    val AMERICA_TORTOLA = ZoneId.of("America/Tortola")
    val AMERICA_VANCOUVER = ZoneId.of("America/Vancouver")
    val AMERICA_VIRGIN = ZoneId.of("America/Virgin")
    val AMERICA_WHITEHORSE = ZoneId.of("America/Whitehorse")
    val AMERICA_YAKUTAT = ZoneId.of("America/Yakutat")
    val AMERICA_YELLOWKNIFE = ZoneId.of("America/Yellowknife")

    val ANTARCTICA_CASEY = ZoneId.of("Antarctica/Casey")
    val ANTARCTICA_DAVIS = ZoneId.of("Antarctica/Davis")
    val ANTARCTICA_DUMONTDURVILLE = ZoneId.of("Antarctica/DumontDUrville")
    val ANTARCTICA_MACQUARIE = ZoneId.of("Antarctica/Macquarie")
    val ANTARCTICA_MAWSON = ZoneId.of("Antarctica/Mawson")
    val ANTARCTICA_MCMURDO = ZoneId.of("Antarctica/McMurdo")
    val ANTARCTICA_PALMER = ZoneId.of("Antarctica/Palmer")
    val ANTARCTICA_ROTHERA = ZoneId.of("Antarctica/Rothera")
    val ANTARCTICA_SOUTH_POLE = ZoneId.of("Antarctica/South_Pole")
    val ANTARCTICA_SYOWA = ZoneId.of("Antarctica/Syowa")
    val ANTARCTICA_TROLL = ZoneId.of("Antarctica/Troll")
    val ANTARCTICA_VOSTOK = ZoneId.of("Antarctica/Vostok")

    val ARCTIC_LONGYEARBYEN = ZoneId.of("Arctic/Longyearbyen")

    val ATLANTIC_AZORES = ZoneId.of("Atlantic/Azores")
    val ATLANTIC_BERMUDA = ZoneId.of("Atlantic/Bermuda")
    val ATLANTIC_CANARY = ZoneId.of("Atlantic/Canary")
    val ATLANTIC_CAPE_VERDE = ZoneId.of("Atlantic/Cape_Verde")
    val ATLANTIC_FAEROE = ZoneId.of("Atlantic/Faeroe")
    val ATLANTIC_FAROE = ZoneId.of("Atlantic/Faroe")
    val ATLANTIC_JAN_MAYEN = ZoneId.of("Atlantic/Jan_Mayen")
    val ATLANTIC_MADEIRA = ZoneId.of("Atlantic/Madeira")
    val ATLANTIC_REYKJAVIK = ZoneId.of("Atlantic/Reykjavik")
    val ATLANTIC_ST_HELENA = ZoneId.of("Atlantic/St_Helena")
    val ATLANTIC_STANLEY = ZoneId.of("Atlantic/Stanley")

    val AUSTRALIA_ACT = ZoneId.of("Australia/ACT")
    val AUSTRALIA_ADELAIDE = ZoneId.of("Australia/Adelaide")
    val AUSTRALIA_BROKEN_HILL = ZoneId.of("Australia/Broken_Hill")
    val AUSTRALIA_BRISBANE = ZoneId.of("Australia/Brisbane")
    val AUSTRALIA_CANBERRA = ZoneId.of("Australia/Canberra")
    val AUSTRALIA_CURRIE = ZoneId.of("Australia/Currie")
    val AUSTRALIA_DARWIN = ZoneId.of("Australia/Darwin")
    val AUSTRALIA_EUCLA = ZoneId.of("Australia/Eucla")
    val AUSTRALIA_HOBART = ZoneId.of("Australia/Hobart")
    val AUSTRALIA_LHI = ZoneId.of("Australia/LHI")
    val AUSTRALIA_LINDEMAN = ZoneId.of("Australia/Lindeman")
    val AUSTRALIA_LORD_HOWE = ZoneId.of("Australia/Lord_Howe")
    val AUSTRALIA_MELBOURNE = ZoneId.of("Australia/Melbourne")
    val AUSTRALIA_NORTH = ZoneId.of("Australia/North")
    val AUSTRALIA_NSW = ZoneId.of("Australia/NSW")
    val AUSTRALIA_PERTH = ZoneId.of("Australia/Perth")
    val AUSTRALIA_QUEENSLAND = ZoneId.of("Australia/Queensland")
    val AUSTRALIA_SOUTH = ZoneId.of("Australia/South")
    val AUSTRALIA_TASMANIA = ZoneId.of("Australia/Tasmania")
    val AUSTRALIA_VICTORIA = ZoneId.of("Australia/Victoria")
    val AUSTRALIA_WEST = ZoneId.of("Australia/West")

    val BRAZIL_ACRE = ZoneId.of("Brazil/Acre")
    val BRAZIL_DENORONHA = ZoneId.of("Brazil/DeNoronha")
    val BRAZIL_EAST = ZoneId.of("Brazil/East")
    val BRAZIL_WEST = ZoneId.of("Brazil/West")

    val CANADA_ATLANTIC = ZoneId.of("Canada/Atlantic")
    val CANADA_CENTRAL = ZoneId.of("Canada/Central")
    val CANADA_EASTERN = ZoneId.of("Canada/Eastern")
    val CANADA_NEWFOUNDLAND = ZoneId.of("Canada/Newfoundland")
    val CANADA_PACIFIC = ZoneId.of("Canada/Pacific")
    val CANADA_SASKATCHEWAN = ZoneId.of("Canada/Saskatchewan")
    val CANADA_MOUNTAIN = ZoneId.of("Canada/Mountain")
    val CANADA_YUKON = ZoneId.of("Canada/Yukon")

    val CHILE_CONTINENTAL = ZoneId.of("Chile/Continental")
    val CHILE_EASTERISLAND = ZoneId.of("Chile/EasterIsland")

    val CST6CDT = ZoneId.of("CST6CDT")

    val CUBA = ZoneId.of("Cuba")

    val CET = ZoneId.of("CET")

    val EET = ZoneId.of("EET")
    val EIRE = ZoneId.of("Eire")
    val EST5EDT = ZoneId.of("EST5EDT")

    val EGYPT = ZoneId.of("Egypt")

    val EUROPE_AMSTERDAM = ZoneId.of("Europe/Amsterdam")
    val EUROPE_ANDORRA = ZoneId.of("Europe/Andorra")
    val EUROPE_ATHENS = ZoneId.of("Europe/Athens")
    val EUROPE_ASTRAKHAN = ZoneId.of("Europe/Astrakhan")
    val EUROPE_BELGRADE = ZoneId.of("Europe/Belgrade")
    val EUROPE_BELFAST = ZoneId.of("Europe/Belfast")
    val EUROPE_BERLIN = ZoneId.of("Europe/Berlin")
    val EUROPE_BUDAPEST = ZoneId.of("Europe/Budapest")
    val EUROPE_BUCHAREST = ZoneId.of("Europe/Bucharest")
    val EUROPE_BRATISLAVA = ZoneId.of("Europe/Bratislava")
    val EUROPE_BRUSSELS = ZoneId.of("Europe/Brussels")
    val EUROPE_BUSINGEN = ZoneId.of("Europe/Busingen")
    val EUROPE_COPENHAGEN = ZoneId.of("Europe/Copenhagen")
    val EUROPE_CHISINAU = ZoneId.of("Europe/Chisinau")
    val EUROPE_DUBLIN = ZoneId.of("Europe/Dublin")
    val EUROPE_GIBRALTAR = ZoneId.of("Europe/Gibraltar")
    val EUROPE_GUERNSEY = ZoneId.of("Europe/Guernsey")
    val EUROPE_HELSINKI = ZoneId.of("Europe/Helsinki")
    val EUROPE_ISTANBUL = ZoneId.of("Europe/Istanbul")
    val EUROPE_ISLE_OF_MAN = ZoneId.of("Europe/Isle_of_Man")
    val EUROPE_JERSEY = ZoneId.of("Europe/Jersey")
    val EUROPE_KALININGRAD = ZoneId.of("Europe/Kaliningrad")
    val EUROPE_KIEV = ZoneId.of("Europe/Kiev")
    val EUROPE_KIROV = ZoneId.of("Europe/Kirov")
    val EUROPE_KIEV_ALT = ZoneId.of("Europe/Kyiv")
    val EUROPE_KYIV = ZoneId.of("Europe/Kyiv")
    val EUROPE_LISBON = ZoneId.of("Europe/Lisbon")
    val EUROPE_LJUBLJANA = ZoneId.of("Europe/Ljubljana")
    val EUROPE_LONDON = ZoneId.of("Europe/London")
    val EUROPE_LUXEMBOURG = ZoneId.of("Europe/Luxembourg")
    val EUROPE_MADRID = ZoneId.of("Europe/Madrid")
    val EUROPE_MALTA = ZoneId.of("Europe/Malta")
    val EUROPE_MARIEHAMN = ZoneId.of("Europe/Mariehamn")
    val EUROPE_MINSK = ZoneId.of("Europe/Minsk")
    val EUROPE_MONACO = ZoneId.of("Europe/Monaco")
    val EUROPE_MOSCOW = ZoneId.of("Europe/Moscow")
    val EUROPE_NICOSIA = ZoneId.of("Europe/Nicosia")
    val EUROPE_NICOSIA_ALT = ZoneId.of("Europe/Nicosia")
    val EUROPE_OSLO = ZoneId.of("Europe/Oslo")
    val EUROPE_PARIS = ZoneId.of("Europe/Paris")
    val EUROPE_PODGORICA = ZoneId.of("Europe/Podgorica")
    val EUROPE_PRAGUE = ZoneId.of("Europe/Prague")
    val EUROPE_RIGA = ZoneId.of("Europe/Riga")
    val EUROPE_ROME = ZoneId.of("Europe/Rome")
    val EUROPE_SARAJEVO = ZoneId.of("Europe/Sarajevo")
    val EUROPE_SAMARA = ZoneId.of("Europe/Samara")
    val EUROPE_SAN_MARINO = ZoneId.of("Europe/San_Marino")
    val EUROPE_SIMFEROPOL = ZoneId.of("Europe/Simferopol")
    val EUROPE_SKOPJE = ZoneId.of("Europe/Skopje")
    val EUROPE_SOFIA = ZoneId.of("Europe/Sofia")
    val EUROPE_STOCKHOLM = ZoneId.of("Europe/Stockholm")
    val EUROPE_TALLINN = ZoneId.of("Europe/Tallinn")
    val EUROPE_TIRASPOL = ZoneId.of("Europe/Tiraspol")
    val EUROPE_TIRANE = ZoneId.of("Europe/Tirane")
    val EUROPE_ULYANOVSK = ZoneId.of("Europe/Ulyanovsk")
    val EUROPE_UZHGOROD = ZoneId.of("Europe/Uzhgorod")
    val EUROPE_VADUZ = ZoneId.of("Europe/Vaduz")
    val EUROPE_VATICAN = ZoneId.of("Europe/Vatican")
    val EUROPE_VIENNA = ZoneId.of("Europe/Vienna")
    val EUROPE_VILNIUS = ZoneId.of("Europe/Vilnius")
    val EUROPE_VOLGOGRAD = ZoneId.of("Europe/Volgograd")
    val EUROPE_ZAGREB = ZoneId.of("Europe/Zagreb")
    val EUROPE_ZAPOROZHYE = ZoneId.of("Europe/Zaporozhye")

    val GB = ZoneId.of("GB")
    val GB_EIRE = ZoneId.of("GB-Eire")

    val GMT = ZoneId.of("GMT")
    val GREENWICH = ZoneId.of("Greenwich")

    val HONGKONG = ZoneId.of("Hongkong")

    val ICELAND = ZoneId.of("Iceland")

    val INDIAN_CHAGOS = ZoneId.of("Indian/Chagos")
    val INDIAN_CHRISTMAS = ZoneId.of("Indian/Christmas")
    val INDIAN_COCOS = ZoneId.of("Indian/Cocos")
    val INDIAN_KERGUELEN = ZoneId.of("Indian/Kerguelen")
    val INDIAN_MAHE = ZoneId.of("Indian/Mahe")
    val INDIAN_MALDIVES = ZoneId.of("Indian/Maldives")
    val INDIAN_MAYOTTE = ZoneId.of("Indian/Mayotte")
    val INDIAN_REUNION = ZoneId.of("Indian/Reunion")

    val IRAN = ZoneId.of("Iran")

    val ISRAEL = ZoneId.of("Israel")

    val JAPAN = ZoneId.of("Japan")

    val JAMAICA = ZoneId.of("Jamaica")

    val KWAJALEIN = ZoneId.of("Kwajalein")

    val LIBYA = ZoneId.of("Libya")

    val MET = ZoneId.of("MET")

    val MEXICO_BAJANORTE = ZoneId.of("Mexico/BajaNorte")
    val MEXICO_BAJASUR = ZoneId.of("Mexico/BajaSur")
    val MEXICO_GENERAL = ZoneId.of("Mexico/General")

    val NAVAJO = ZoneId.of("Navajo")

    val NZ = ZoneId.of("NZ")
    val NZ_CHAT = ZoneId.of("NZ-CHAT")

    val POLAND = ZoneId.of("Poland")

    val PORTUGAL = ZoneId.of("Portugal")

    val PRC = ZoneId.of("PRC")

    val PST8PDT = ZoneId.of("PST8PDT")

    val ROK = ZoneId.of("ROK")

    val SINGAPORE = ZoneId.of("Singapore")

    val SYSTEMV_AST4 = ZoneId.of("SystemV/AST4")
    val SYSTEMV_AST4ADT = ZoneId.of("SystemV/AST4ADT")
    val SYSTEMV_CST6 = ZoneId.of("SystemV/CST6")
    val SYSTEMV_CST6CDT = ZoneId.of("SystemV/CST6CDT")
    val SYSTEMV_EST5EDT = ZoneId.of("SystemV/EST5EDT")
    val SYSTEMV_HST10 = ZoneId.of("SystemV/HST10")
    val SYSTEMV_MST7 = ZoneId.of("SystemV/MST7")
    val SYSTEMV_MST7MDT = ZoneId.of("SystemV/MST7MDT")
    val SYSTEMV_PST8 = ZoneId.of("SystemV/PST8")
    val SYSTEMV_PST8PDT = ZoneId.of("SystemV/PST8PDT")
    val SYSTEMV_YST9 = ZoneId.of("SystemV/YST9")
    val SYSTEMV_YST9YDT = ZoneId.of("SystemV/YST9YDT")

    val TURKEY = ZoneId.of("Turkey")

    val US_ALEUTIAN = ZoneId.of("US/Aleutian")
    val US_ALASKA = ZoneId.of("US/Alaska")
    val US_ARIZONA = ZoneId.of("US/Arizona")
    val US_CENTRAL = ZoneId.of("US/Central")
    val US_EASTERN = ZoneId.of("US/Eastern")
    val US_EAST_Indiana = ZoneId.of("US/East-Indiana")
    val US_HAWAII = ZoneId.of("US/Hawaii")
    val US_INDIANA_Starke = ZoneId.of("US/Indiana-Starke")
    val US_MICHIGAN = ZoneId.of("US/Michigan")
    val US_MOUNTAIN = ZoneId.of("US/Mountain")
    val US_PACIFIC = ZoneId.of("US/Pacific")
    val US_SAMOA = ZoneId.of("US/Samoa")

    val UTC = ZoneId.of("UTC")

    val UCT = ZoneId.of("UCT")

    val UNIVERSAL = ZoneId.of("Universal")

    val WET = ZoneId.of("WET")
    val W_SU = ZoneId.of("W-SU")

    val ZULU = ZoneId.of("Zulu")
}
